import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const json = async (name) => JSON.parse(await readFile(new URL("./data/" + name, import.meta.url), "utf8"));
const [reviews, analysis, registry, retailers] = await Promise.all([
  json("reviews_normalized.json"), json("analysis_output.json"), json("sku_registry.json"), json("retailer_evidence.json")
]);

assert.equal(registry.products.length, 8);
assert.equal(reviews.length, 593);
const eligible = reviews.filter((r) => r.metric_eligible !== false);
assert.equal(eligible.length, 588);
assert.equal(eligible.filter((r) => r.date >= "2024-11-01" && r.date <= "2026-07-15").length, 203);
assert.deepEqual([...new Set(eligible.map((r) => r.source))].sort(), ["Amazon", "Kevin's Natural Foods", "Kroger", "Target"]);
assert.ok(reviews.every((r) => registry.products.some((p) => p.id === r.product_id)));
assert.ok(reviews.every((r) => !/bolognese|chicken/i.test(r.product)));
assert.ok(reviews.every((r) => r.date >= "2023-01-01"));
assert.equal(analysis.data_quality.amazon_exact_duplicate_rows_removed, 540);
assert.equal(retailers.rating_snapshots.length, 5);
assert.equal(analysis.rating_snapshots.length, 13);
assert.equal(analysis.rating_snapshots.filter((item) => item.source === "Kevin's Natural Foods").length, 8);
assert.equal(analysis.assortment_snapshots.length, 11);
assert.equal(analysis.assortment_snapshots.filter((item) => item.source === "Costco").length, 6);
assert.equal(eligible.filter((r) => r.source === "Kroger").length, 26);
assert.equal(eligible.filter((r) => r.source === "Kevin's Natural Foods").length, 422);
assert.equal(eligible.filter((r) => r.product_id === "peppercorn_steak_tips").length, 56);
assert.equal(eligible.filter((r) => r.product_id === "chimichurri_beef").length, 12);
assert.equal(eligible.filter((r) => r.product_id === "sirloin_mushroom").length, 2);
assert.ok(reviews.filter((r) => r.source === "Kevin's Natural Foods").every((r) => !("reviewer_name" in r)));

const files = await Promise.all(["index.html", "styles.css", "app.js", "README.md"].map((name) => readFile(new URL("./" + name, import.meta.url), "utf8")));
assert.ok(!/(chatgpt|codex|openai|artificial intelligence|generated by)/i.test(files.join("\n")));
assert.match(files[0], /Export filtered CSV/);
assert.match(files[2], /filteredReviews/);
console.log("Dashboard integrity checks passed.");
