import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const json = async (name) => JSON.parse(await readFile(new URL("./data/" + name, import.meta.url), "utf8"));
const [reviews, analysis, registry, retailers] = await Promise.all([
  json("reviews_normalized.json"), json("analysis_output.json"), json("sku_registry.json"), json("retailer_evidence.json")
]);

assert.equal(registry.products.length, 8);
assert.equal(reviews.length, 153);
assert.equal(reviews.filter((r) => r.date >= "2024-11-01" && r.date <= "2026-07-14").length, 116);
assert.deepEqual([...new Set(reviews.map((r) => r.source))].sort(), ["Amazon", "Kroger", "Target", "Walmart"]);
assert.ok(reviews.every((r) => registry.products.some((p) => p.id === r.product_id)));
assert.ok(reviews.every((r) => !/bolognese|chicken/i.test(r.product)));
assert.equal(analysis.data_quality.amazon_exact_duplicate_rows_removed, 540);
assert.equal(retailers.rating_snapshots.length, 5);

const files = await Promise.all(["index.html", "styles.css", "app.js", "README.md"].map((name) => readFile(new URL("./" + name, import.meta.url), "utf8")));
assert.ok(!/(chatgpt|codex|openai|artificial intelligence|generated by)/i.test(files.join("\n")));
assert.match(files[0], /Export filtered CSV/);
assert.match(files[2], /filteredReviews/);
console.log("Dashboard integrity checks passed.");
