import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const json = async (name) => JSON.parse(await readFile(new URL("./data/" + name, import.meta.url), "utf8"));
const [reviews, analysis, registry, retailers, retailerMatchAudit, competitorReviews, competitorSnapshots, competitorCoverage] = await Promise.all([
  json("reviews_normalized.json"), json("analysis_output.json"), json("sku_registry.json"), json("retailer_evidence.json"), json("kevin_retailer_match_audit.json"), json("competitor_reviews_normalized.json"), json("competitor_rating_snapshots.json"), json("competitor_coverage_audit.json")
]);

assert.equal(registry.products.length, 8);
assert.equal(registry.identity_authority.verification_status, "eight_scoped_products_verified");
assert.equal(retailerMatchAudit.rows.length, 48);
assert.deepEqual(retailerMatchAudit.sources_audited, ["Brand", "Target", "Amazon", "Kroger", "Walmart", "Costco"]);
assert.ok(registry.products.every((product) => product.shopify_product_id && product.find_a_store_url && product.upcs.length));
assert.ok(retailerMatchAudit.rows.filter((row) => row.source === "Brand").every((row) => row.status === "owned_site_verified"));
assert.equal(reviews.length, 640);
const eligible = reviews.filter((r) => r.metric_eligible !== false);
assert.equal(eligible.length, 638);
assert.equal(eligible.filter((r) => r.date >= "2024-11-01" && r.date <= "2026-07-22").length, 247);
assert.deepEqual([...new Set(eligible.map((r) => r.source))].sort(), ["Amazon", "Kevin's Natural Foods", "Kroger", "Target", "Walmart"]);
assert.ok(reviews.every((r) => registry.products.some((p) => p.id === r.product_id)));
assert.ok(reviews.every((r) => !/bolognese|chicken/i.test(r.product)));
assert.ok(reviews.every((r) => r.date >= "2023-01-01"));
assert.equal(analysis.data_quality.amazon_exact_duplicate_rows_removed, 540);
assert.equal(retailers.rating_snapshots.length, 5);
assert.equal(analysis.rating_snapshots.length, 15);
assert.equal(analysis.rating_snapshots.filter((item) => item.source === "Kevin's Natural Foods").length, 8);
assert.equal(analysis.as_of, "2026-07-22");
assert.equal(analysis.data_quality.walmart_complete_written_reviews, 48);
assert.equal(analysis.assortment_snapshots.length, 11);
assert.equal(analysis.assortment_snapshots.filter((item) => item.source === "Costco").length, 6);
assert.equal(eligible.filter((r) => r.source === "Kroger").length, 26);
assert.equal(eligible.filter((r) => r.source === "Kevin's Natural Foods").length, 422);
assert.equal(eligible.filter((r) => r.source === "Target").length, 122);
assert.equal(eligible.filter((r) => r.source === "Walmart").length, 48);
assert.equal(new Set(eligible.filter((r) => r.source === "Walmart").map((r) => r.provider_review_id)).size, 48);
assert.equal(eligible.filter((r) => r.product_id === "peppercorn_steak_tips").length, 56);
assert.equal(eligible.filter((r) => r.product_id === "chimichurri_beef").length, 12);
assert.equal(eligible.filter((r) => r.product_id === "sirloin_mushroom").length, 2);
assert.ok(reviews.filter((r) => r.source === "Kevin's Natural Foods").every((r) => !("reviewer_name" in r)));
assert.equal(competitorReviews.filter((r) => r.metric_eligible !== false).length, 202);
assert.equal(competitorReviews.filter((r) => r.metric_eligible === false && r.quality_status === "excluded_shared_variant_without_review_level_size").length, 10);
assert.equal(competitorSnapshots.snapshots.length, 21);
assert.equal(competitorSnapshots.snapshots.filter((r) => r.source === "Kroger").length, 6);
assert.equal(competitorSnapshots.snapshots.filter((r) => r.source === "Amazon").length, 5);
assert.equal(competitorSnapshots.snapshots.filter((r) => r.source === "Amazon" && r.metric_eligible !== false).length, 3);
assert.equal(competitorCoverage.rows.length, 78);

const files = await Promise.all(["index.html", "styles.css", "app.js", "README.md"].map((name) => readFile(new URL("./" + name, import.meta.url), "utf8")));
assert.ok(!/(chatgpt|codex|openai|artificial intelligence|generated by)/i.test(files.join("\n")));
assert.match(files[0], /Export filtered CSV/);
assert.match(files[0], /KNF_Beef_HMR_Executive_One_Pager_2026-07-22\.pdf/);
assert.match(files[0], /KNF_Competitor_Review_Comparison_Executive_One_Pager\.pdf/);
assert.match(files[2], /filteredReviews/);
assert.match(files[2], /renderExecutiveComparison/);
assert.match(files[2], /comparisonView/);
await readFile(new URL("./downloads/KNF_Competitor_Review_Comparison_Executive_One_Pager.pdf", import.meta.url));
console.log("Dashboard integrity checks passed.");
